apropiacion_tecnologica/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'home/', include(('olimpicos.urls',"olimpicos"), namespace="deportista")),
]

olimpicos/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'deportistas/', views.deportistas, name="deportistas"),
    url(r'^add/$', views.add_deportista, name='addDeportista'),
    url(r'^addUser/$', views.add_user_view, name="addUser"),
    url(r'^registerUser', views.add_user, name="registrarUsuario"),
    url(r'login/$', views.login_view, name='login'),
    url(r'^loginUser', views.login_user, name='loginUser'),
    url(r'^logout/$', views.logout_view, name='logout'),
]

olimpicos/models.py
from django.db import models
from django.contrib.auth.models import User
from django.forms import ModelForm


# Create your models here.

class Modalidad(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return 'modalidad: ' + self.nombre

class Deporte(models.Model):
    nombre = models.CharField(max_length=100)
    icono = models.CharField(max_length=200)
    modalidad = models.ForeignKey(Modalidad, on_delete=models.CASCADE)

    def __str__(self):
        return 'deporte: ' + self.nombre + ' icono: ' + self.icono


class Evento(models.Model):
    nombre = models.CharField(max_length=100)
    video = models.CharField(max_length=200)

    def __str__(self):
        return 'evento: ' + self.nombre + ' video: ' + self.video


class Deportista(models.Model):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    lugar_nacimiento = models.CharField(max_length=200)
    fecha_nacimiento = models.DateField()
    edad = models.IntegerField()
    peso = models.FloatField()
    estatura = models.FloatField()
    entrenador = models.CharField(max_length=100)
    foto = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='static', null=True)

    def __str__(self):
        return 'deportista:' + self.nombre + ' ' + self.apellido


class DeportistaForm(ModelForm):
    class Meta:
        model = Deportista
        fields = ['nombre', 'apellido', 'lugar_nacimiento', 'fecha_nacimiento', 'edad', 'peso', 'estatura', 'entrenador', 'foto', 'image']


class Participacion(models.Model):
    fecha = models.DateField()
    hora = models.TimeField()
    resultado = models.FloatField()
    deportista = models.ForeignKey(Deportista, on_delete=models.CASCADE)
    evento = models.ForeignKey(Evento, on_delete=models.CASCADE)
    deporte = models.ForeignKey(Deporte, on_delete=models.CASCADE)
    def __str__(self):
        return 'participacion:' + str(self.fecha) + ' ' + self.deportista.nombre


class Comentario(models.Model):
    contenido = models.CharField(max_length=500)
    fecha = models.TimeField()
    evento = models.ForeignKey(Evento, on_delete=models.CASCADE)
    estudiante = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return "Comentario: " + self.contenido

olimpicos/views.py
from django.shortcuts import render
from .models import Deportista, DeportistaForm, Participacion
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User
import json
from django.core import serializers
from django.contrib.auth import authenticate, login, logout




# Create your views here.
def deportistas(request):
    deportistas_list = Deportista.objects.all()
    participaciones_list = Participacion.objects.all()
    context = {'deportistas_list': deportistas_list, 'participaciones_list': participaciones_list}
    return render(request, 'index.html', context)


def add_deportista(request):
    if request.method == 'POST':
        form = DeportistaForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('deportista:deportistas'))
    else:
            form = DeportistaForm()
    return render(request, 'deportistas.html', {'form': form})

@csrf_exempt
def add_user_view(request):
    if request.method == 'POST':
        jsonUser = json.loads(request.body)
        user_Name = jsonUser['username']
        first_name = jsonUser['first_name']
        last_name = jsonUser['last_name']
        passwords = jsonUser['password']
        email = jsonUser['email']

        user_model = User.objects.create_user(username=user_Name, password=passwords)
        user_model.first_name = first_name
        user_model.last_name = last_name
        user_model.email = email
        user_model.save()
    return HttpResponse(serializers.serialize("json", [user_model]))

@csrf_exempt
def add_user(request):
    return(render(request,"register.html"))


@csrf_exempt
def login_view(request):
    print("Entro")
    if request.method == 'POST':
        jsonUser = json.loads(request.body)
        user_name = jsonUser['username']
        passwords = jsonUser['password']
        user = authenticate(username=user_name, password=passwords)
        if user is not None:
            login(request, user)
            message = "Ok"
        else:
            message = "Nombre de usuario o contraseña incorrecto"
    return JsonResponse({"message": message})

@csrf_exempt
def login_user(request):
    return render(request, "login.html")

@csrf_exempt
def logout_view(request):
    logout(request)
    return JsonResponse({"message": 'Ok'})

olimpicos/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Login</title>
      {% load static %}
      <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
      <link href="/static/css/bulma.css" rel="stylesheet" />
      <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </head>
  <body>
    <section class="hero is-fullheight is-dark">
      <div class="hero-head">
        <nav class="navbar">
          <div class="container">
            <div id="navbarMenuHeroA" class="navbar-menu">
              <div class="navbar-end">
                <a
                  href="{% url 'deportista:deportistas' %}"
                  class="navbar-item"
                >
                  Inicio
                </a>
                <a href="{% url 'deportista:loginUser' %}" class="navbar-item">
                  Login
                </a>
                <a
                  href="{% url 'deportista:registrarUsuario' %}"
                  class="navbar-item"
                >
                  Sign Up
                </a>
              </div>
            </div>
          </div>
        </nav>
      </div>
      <div class="hero-body">
        <div class="container has-text-centered">
          {% block content %} {% endblock %}
        </div>
      </div>
    </section>
  </body>
</html>

olimpicos/templates/deportista.html
{% extends "base.html" %} {% block content %}
<div class="columns">
  <div class="column">
    <div class="columns is-centered">
      {% if deportista.foto %}
      <div class="column">
        <figure class="image is-256x256">
          <img src="/{{ deportista.image }}" />
        </figure>
      </div>
      {% else %}
      <div class="column">
        <figure class="image is-256x256">
          <img src="{{ deportista.foto }}" />
        </figure>
      </div>
      {% endif %}
    </div>
    <div class="columns is-centered">
      <div class="column">
        {% for icono in deportista.iconos %}
        <div class="column-4">
          <figure class="image is-64x64">
            <img src="{{ icono }}" />
          </figure>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
  <div class="column">
    <table class="table is-striped is-narrow is-hoverable is-fullwidth">
      <tr>
        <td>Nombre</td>
        <td>{{deportista.nombre}} {{ deportista.apellido }}</td>
      </tr>
      <tr>
        <td>Lugar de nacimiento</td>
        <td>{{deportista.lugar_nacimiento}}</td>
      </tr>
      <tr>
        <td>Fecha de nacimiento</td>
        <td>{{deportista.fecha_nacimiento}}</td>
      </tr>
      <tr>
        <td>Edad</td>
        <td>{{deportista.edad}}</td>
      </tr>
      <tr>
        <td>Peso</td>
        <td>{{deportista.peso}}</td>
      </tr>
      <tr>
        <td>Estatura</td>
        <td>{{deportista.estatura}}</td>
      </tr>
      <tr>
        <td>Entrenador</td>
        <td>{{deportista.entrenador}}</td>
      </tr>
    </table>
  </div>
</div>
<div class="columns is-centered">
  <div class="column">
    <div class="columns">
      <h2>Participaciones</h2>
    </div>
    <div class="columns is-centered">
      <table class="table is-striped is-narrow is-hoverable is-fullwidth">
        <thead>
          <tr>
            <td>Fecha</td>
            <td>Hora</td>
            <td>Modalidad</td>
            <td>Resultado</td>
            <td>Video</td>
          </tr>
        </thead>
        <tbody>
          {% for participacion in participaciones %}
          <tr>
            <td>{{ participacion.fecha }}</td>
            <td>{{ participacion.hora }}</td>
            <td>{{ participacion.deporte.modalidad }}</td>
            <td>{{ participacion.resultado }}</td>
            <td>
              <a href="/"><i class="fab fa-youtube"></i></a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}

olimpicos/templates/deportistas.html
{% extends "base.html" %} {% block content %}
<form
  action="{%url 'deportista:addDeportista' %}"
  enctype="multipart/form-data"
  method="post"
>
  {% csrf_token %} {{ form.as_p }}
  <input type="submit" value="Adicionar" />
</form>
{% endblock %}

olimpicos/templates/index.html
{% extends "base.html" %} {% block content %}
<div class="container has-text-centered">
  <h2 class="title is-2" align="center">Deportistas</h2>
  <div class="container">
    <div class="row">
      {% for deportista in deportistas_list %}
      <div class="col-sm">
        {% if deportista.image == None %}
        <div class="card" style="width: 18rem">
          <img
            class="card-img-top"
            alt="Card image cap"
            src="{{deportista.foto}}"
          />
          <div class="card-body">
            <h5 class="card-title">
              {{ deportista.nombre }} {{ deportista.apellido }}
            </h5>
            <p class="card-text">{{ deportista.peso }}</p>
            <a href="#" class="btn btn-primary">Mas información</a>
          </div>
        </div>
        {% else %}
        <div class="card" style="width: 300px">
          <img
            class="card-img-top"
            alt="Card image cap"
            style="height: 300px"
            src="/{{ deportista.image }}"
          />
          <div class="card-body">
            <h5 class="card-title">
              {{ deportista.nombre }} {{ deportista.apellido }}
            </h5>
            <div class="container">
              <div class="row">
                {% for participacion in participaciones_list %}
                {% if participacion.deportista.id == deportista.id %}
                <div class="col-sm">
                  <img
                    class="card-img-bottom"
                    alt="Card image cap"
                    style="height: 50px; width: 50px"
                    src="{{ participacion.deporte.icono }}"
                  />
                  <p class="card-text">{{ participacion.deporte.nombre }}</p>
                </div>
                {% endif %} {% endfor %}
              </div>
            </div>
            <a href="#" class="button is-info">Mas información</a>
          </div>
        </div>
        {% endif %}
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

olimpicos/templates/login.html
{% extends "base.html" %} {% block content %}
<div class="container has-text-centered">
  <div class="column is-4 is-offset-4">
    <h3 class="title">Login</h3>
    <div class="box is-dark">
      <form method="post" action="" onsubmit="return sendForm();">
        <div class="field">
          <div class="control">
            <input
              class="input is-medium"
              type="text"
              id="username"
              name="username"
              placeholder="Usuario"
              required
            />
          </div>
        </div>
        <div class="field">
          <div class="control">
            <input
              class="input is-medium"
              type="password"
              id="password"
              name="password"
              placeholder="Password"
              required
            />
          </div>
        </div>
        <div class="columns">
          <div class="column is-half">
            <input
              class="is-fullwidth button is-block is-info is-large"
              id="send"
              name="send"
              type="submit"
              value="login"
            />
          </div>
          <div class="column is-half">
            <a
              class="is-fullwidth button is-block is-danger is-large"
              href="http://127.0.0.1:8000/home/deportistas/"
              >Cancelar</a
            >
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

<script>
  function sendForm() {
    $.ajax({
      type: "POST",
      url: "http://127.0.0.1:8000/home/login/",
      data: JSON.stringify({
        username: $("#username").val(),
        password: $("#password").val(),
      }),
      contentType: "application/json; charset=utf-8",
      dataType: "json",
      success: function (data) {
        if (data.message == "Ok") {
          window.location = "http://127.0.0.1:8000/home/deportistas/";
        } else {
          alert("Se presento un error en el login");
        }
      },
      failure: function (errMsg) {
        alert("Se presentó un problema al realizar el login");
      },
    });
    return false;
  }
</script>
{% endblock %}

olimpicos/templates/register.html
{% extends "base.html" %} {% block content %}
<div class="container has-text-centered">
  <div class="column is-4 is-offset-4">
    <h3 class="title">Registro</h3>
    <div class="box is-dark">
      <form method="post" action="" onsubmit="return sendForm();">
        <div class="field">
          <div class="control">
            <input
              class="input is-medium"
              type="text"
              id="username"
              name="username"
              placeholder="Usuario"
              required
            />
          </div>
        </div>
        <div class="field">
          <div class="control">
            <input
              class="input is-medium"
              type="text"
              id="first_name"
              name="firs_name"
              placeholder="Nombre"
              required
            />
          </div>
        </div>
        <div class="field">
          <div class="control">
            <input
              class="input is-medium"
              type="text"
              id="last_name"
              name="last_name"
              placeholder="Apellido"
              required
            />
          </div>
        </div>
        <div class="field">
          <div class="control">
            <input
              class="input is-medium"
              type="email"
              id="email"
              name="email"
              placeholder="ejemplo@correo.com"
              required
            />
          </div>
        </div>
        <div class="field">
          <div class="control">
            <input
              class="input is-medium"
              type="password"
              id="password2"
              name="password2"
              placeholder="Contraseña"
              required
            />
          </div>
        </div>
        <div class="field">
          <div class="control">
            <input
              class="input is-medium"
              type="password"
              id="password"
              name="password"
              placeholder="Comprobación de contraseña"
              required
            />
          </div>
        </div>
        <div class="columns">
          <div class="column is-half">
            <input
              class="is-fullwidth button is-block is-info is-large"
              id="send"
              name="send"
              type="submit"
              value="Registrarse"
            />
          </div>
          <div class="column is-half">
            <a
              class="is-fullwidth button is-block is-danger is-large"
              href="http://127.0.0.1:8000/home/deportistas/"
              >Cancelar</a
            >
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
<script>
  function sendForm() {
    if ($("#password").val() != $("#password2").val()) {
      alert("Las contraseñas no son iguales");
      return false;
    }
    $.ajax({
      type: "POST",
      url: "http://127.0.0.1:8000/home/addUser/",
      data: JSON.stringify({
        username: $("#username").val(),
        first_name: $("#first_name").val(),
        last_name: $("#last_name").val(),
        password: $("#password").val(),
        email: $("#email").val(),
      }),
      contentType: "application/json; charset=utf-8",
      dataType: "json",
      success: function (data) {
        alert("Usuario registrado: " + $("#username").val());
        window.location = "http://127.0.0.1:8000/home/deportistas";
      },
      failure: function (errMsg) {
        print("Problema");
        alert("Se presentó un problema");
      },
    });
    return false;
  }
</script>
{% endblock %}

olimpicos/templates/video.html
{% extends "base.html" %} {% block content %}
<iframe
  width="560"
  height="315"
  src="{{ video }}"
  frameborder="0"
  allow="accelerometer; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
  allowfullscreen
></iframe>
<h2 class="title is-2">Comentarios</h2>
{% endblock %}